name: fruitonest
description: A comprehensive fruit e-commerce platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  
  # Firebase - Updated to compatible versions
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  firebase_messaging: ^15.1.3
  
  # State Management
  provider: ^6.1.2
  
  # UI Components
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  carousel_slider: ^5.0.0
  badges: ^3.1.2
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  share_plus: ^10.0.3
  flutter_image_compress: ^2.4.0
  
  google_fonts: ^6.1.0