name: fruitonest
description: A comprehensive fruit e-commerce platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10
  
  # State Management
  provider: ^6.1.1
  
  # UI Components
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  carousel_slider: ^4.2.1
  badges: ^3.1.2
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.3.3
  url_launcher: ^6.2.4
  share_plus: ^7.2.2