// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6VyrJ1-opuZn1J3f4hghLIW0U16VkMYo',
    appId: '1:544128131405:web:f829c387fcb0ee4982d704',
    messagingSenderId: '544128131405',
    projectId: 'fruitonest',
    authDomain: 'fruitonest.firebaseapp.com',
    storageBucket: 'fruitonest.firebasestorage.app',
    measurementId: 'G-7L2WCHR4BZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAao5-AMsO_HMRtzB0VHCDBjoUPJ_l5afI',
    appId: '1:544128131405:android:d9ea6422e40e63f882d704',
    messagingSenderId: '544128131405',
    projectId: 'fruitonest',
    storageBucket: 'fruitonest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPVzA52kCQeL9-qFRy2z1XnMf4zgeT4-Y',
    appId: '1:544128131405:ios:eee733e974b81f0482d704',
    messagingSenderId: '544128131405',
    projectId: 'fruitonest',
    storageBucket: 'fruitonest.firebasestorage.app',
    iosBundleId: 'com.example.fruitonest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPVzA52kCQeL9-qFRy2z1XnMf4zgeT4-Y',
    appId: '1:544128131405:ios:eee733e974b81f0482d704',
    messagingSenderId: '544128131405',
    projectId: 'fruitonest',
    storageBucket: 'fruitonest.firebasestorage.app',
    iosBundleId: 'com.example.fruitonest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6VyrJ1-opuZn1J3f4hghLIW0U16VkMYo',
    appId: '1:544128131405:web:0b827283f7ef31dd82d704',
    messagingSenderId: '544128131405',
    projectId: 'fruitonest',
    authDomain: 'fruitonest.firebaseapp.com',
    storageBucket: 'fruitonest.firebasestorage.app',
    measurementId: 'G-3SDB26GB8V',
  );
}
